# Generated by `nixos-generate-config` on the server laptop (2026-07-14).
# BIOS machine: GRUB on the /dev/sda MBR (configured in ./default.nix), so
# there is no /boot filesystem here.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "uhci_hcd"
    "ehci_pci"
    "ahci"
    "firewire_ohci"
    "sd_mod"
    "sr_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2205dfc5-d7da-4e30-a6a3-6047d64bfcd5";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/3bb1bc48-349b-46b5-8188-d3d272a8265a"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
